DROP database IF EXISTS `g7`;

CREATE database IF NOT EXISTS `g7`;
use `g7`;

CREATE TABLE `USER` (
  `ID` varchar(100) NOT NULL,
  `EMAIL` varchar(100) NOT NULL UNIQUE,
  `PASSWORD` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


INSERT INTO `STUDENT` (`ID`,`EMAIL`,`PASSWORD`) VALUES ('111','test1@gmail.com','11111111');
INSERT INTO `STUDENT` (`ID`,`EMAIL`,`PASSWORD`) VALUES ('222','test2@gmail.com','22222222');