version: "3.9"  # optional since v1.27.0
services:
  message_queue:
    image: ${mq_image:-rabbitmq}
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  spring-boot:
    build:
      context: .
      dockerfile: quickstart/dockerfiles/springboot/Dockerfile
    ports:
      - "8080:8080"
    command: bash -c "java -jar /opt/ddd/web-*.jar --spring.config.location=/opt/ddd/properties/quickstart.properties"
    environment:
      - PERSISTENCE_TYPE=memory
      - RBMQ_USER="${rbmq_user:-admin}"
      - RBMQ_PASSWORD="${rbmq_password:-admin}"
      - RBMQ_HOST="${rbmq_host:-127.0.0.1}"
    depends_on:
      - message_queue


