version: "3.9"  # optional since v1.27.0
services:
  postgre:
    image: postgres:9.6.21-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=ddd
      - POSTGRES_DB=ddd
      - POSTGRES_USER=ddd
    ports:
      - "5432:5432"
  migration:
    image: flyway/flyway:7
    command: -url=jdbc:postgresql://postgre:5432/ddd -schemas=public -user=ddd -password=ddd -connectRetries=60 migrate
    volumes:
      - ./migration/sql:/flyway/sql
    depends_on:
      - postgre




