version: "3.9"  # optional since v1.27.0
services:
  message_queue:
    image: ${mq_image:-rabbitmq}
      restart: always
      ports:
        - "5672:5672"
        - "15672:15672"
  spring-boot:
    environment:
      - LAUNCH_TYPE=QUICKSTART_RABBITMQ
      - PERSISTENCE_TYPE=rdbms
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
      - RABBITMQ_HOST=127.0.0.1
    depends_on:
      - message_queue
