

DROP TABLE  IF EXISTS `USER`;

CREATE TABLE `USER` (
  `ID` varchar(100) NOT NULL,
  `EMAIL` varchar(100) NOT NULL UNIQUE,
  `PASSWORD` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
